### ISSUE TITLE
Selective clearing of varnish cache instead of restarting

### ISSUE THREAD

**Issue by kasperg** [reload/deployotron#18]
When deploying the only way to clear the varnish cache is to restart the server. This is unfortunate if there are several sites running on the same server.

An alternative approach could be to [ban all cache entries for the domain we deploy to](https://gist.github.com/aderowbotham/5517123).

**Comment by xendk** [comment]
Now that Varnish clearing is just a matter of passing the right command in post-cc-all, this is obsoleted.
