### ISSUE TITLE
Move git fetch to SanityCheck

### ISSUE THREAD

**Issue by xendk** [reload/deployotron#24]
Moving the fetching out of deploy would mean lower downtime. 

Secondly, we can check if the ref is available and catch errors linke forgetting to push earlier, and without setting the site offline.

**Comment by rajibmp** [comment]
To add to this, I have faced several issue like Deploytron doesn't fetch from the git repo properly. It uses fetch and checkout, sometimes might not be ideal solution. Git pull with force option could be.

**Comment by xendk** [comment]
Git pull is just shorthand for git fetch and git pull. Force is passed to fetch and is described as:

>  When git fetch is used with <rbranch>:<lbranch> refspec, it refuses to update the local branch <lbranch> unless the remote branch <rbranch> it fetches is a descendant of <lbranch>. This option overrides that check.

So force pushes could make it unhappy per default, but I'm wary of using `--force` per default, as having new deployments not being the descendant of the previous is a pretty good indicator you're doing something wrong.

**Comment by xendk** [comment]
@rajibmp How does it fail when it does this?

**Comment by rajibmp** [comment]
> Git pull is just shorthand for git fetch and git pull  

maybe you mean git merge. BTW force fetch doesn't change anything.

I don't mean force push, but force pull... Usually the workflow is: I do development in my local machine and push it to git repo, from git repo I git pull it to server. Now I am using Deployotron in server, so, it could do git pull, and other cool drupal stuffs like features reverts etc.

right now If I run Deploytron then it completes the deploy but it doesn't pull the changes from the git repo. For instance my previous commit was at: *ab3ut8c* and I have made changes in my git repo, then I run Deployotron, after finishing the deploy when I checked the gitlog the commit is still the old one not the new one from git repo. If I do manually git pull in the repo and run deploy again, it still runs perfectly though, the only thing is I am doing git pull in the location manually.

**Comment by rajibmp** [comment]
I am yet to try but maybe I'll give it a shot by adding git merge directly in the code.... Found the reference code here: - 

https://github.com/reload/deployotron/blob/master/deployotron.actions.inc#L680

```php
if (!$this->sh('git fetch')) {
        $message = $this->shOutput();
        if (preg_match('/Permission denied \(publickey\)/', $message)) {
          drush_log(dt('Access denied to repository URL.'), 'error');
          drush_log(dt('Ensure that either that the user on the server has access to the repository, or use "ForwardAgent yes" in .ssh/config.'), 'error');
        }
        else {
          drush_print($message);
        }
        return drush_set_error(dt("Could not fetch from remote repository."));
      }

      if (!$this->sh('git checkout ' . $this->sha)) {
        $message = $this->shOutput();
        if (preg_match('/^fatal: reference is not a tree/', $message)) {
          drush_log(dt('Could not find SHA, did you forget to push?'), 'error');
        }
        else {
          drush_print($message);
        }
        return drush_set_error(dt('Could not checkout code.'));
      }
```

Will try to replace something like: - 

```php
if (!$this->sh('git pull -u ORIGIN BRANCHNAME')) {
        $message = $this->shOutput();
        if (preg_match('/Permission denied \(publickey\)/', $message)) {
          drush_log(dt('Access denied to repository URL.'), 'error');
          drush_log(dt('Ensure that either that the user on the server has access to the repository, or use "ForwardAgent yes" in .ssh/config.'), 'error');
        }
        else {
          drush_print($message);
        }
        return drush_set_error(dt("Could not pull from remote repository."));
      }

```

If there is something I should consider here then I appreciate your help, specially in **origin** and **branchname**.

**Comment by xendk** [comment]
Yes, I meant `git merge`. My point being that `git pull` doesn't do anything that `git fetch` and `git merge` doesn't, it's just a wrapper to run those two commands with one.

Indeed, the `-u` switch you use in your code is simply passed on to `git fetch` and the documentation says:

>       -u, --update-head-ok
>           By default git fetch refuses to update the head which corresponds
>           to the current branch. This flag disables the check. This is purely
>           for the internal use for git pull to communicate with git fetch,
>           and unless you are implementing your own Porcelain you are not
>           supposed to use it.

Which basically, as I understand it, fixes the checked out branch to be the same as the just fetched branch. Assuming the current branch is the same as the fetched.

However, Deployotron does not merge. It checks out the specific sha which becomes a detached head. It does this to ensure that what's deployed is exactly what's in the commit that's being deployed. If it did a merge, there's no guarantee as to what was deployed, as anything committed to the checked out branch on the server would be preserved.

So you shouldn't do a `git pull` to fix things, but rather `git fetch origin` and `git checkout deployed-sha`. `git pull` might just mask your real problem. Maybe you've edited a file, and `git checkout` refuses to overwrite your changes, while `git pull` just quietly merges.

You should stop using `git pull -u` as I don't think it does what you think it does. And consider using `git fetch` and `git merge`/`git rebase`, as it gives you the opportunity to review the changes you pull in (using `git diff origin/branch branch`) before deciding whether to merge or rebase.

**Comment by rajibmp** [comment]
well I agree with the point you made. I have noticed the detached HEAD, The only reason I was exploring `git pull`  was Deployotron doesn't checkout to the latest sha from git repo.

As I said earlier: 
* My Commit is at: *ab3ut8c* in the server as Detached head
* I make some changes and push to git repo the current commit sha in **develop** branch is: *ayhsks2*
* I run deploy in the server with `drush deploy @sitename --branch=develop --insanity`
* The deploy process completes, but when I check the `git log` it is still at same old detached HEAD and commit: *ab3ut8c*

I need to pass the Branchname as I am using the same git repo for production and development.

**Comment by xendk** [comment]
Questions/points to investigate:

1. Why `--insanity`?
2. Those aren't sha's. Sha's are hexadecimal. You must be working with tags?
3. Deployotron does not fail, yet the sha hasn't changed? That sounds very fishy, as it specifically checks that the checked out sha matches the requested.
4. What happens if you run `git checkout SHA` manually on the server?
5. What does `git show HEAD` tell you?

**Comment by rajibmp** [comment]
1.) `--insanity` due to file permission issue
 2.) those are supposed to be example not the actual sha from log. Yes I do have git tags too but that's for production. For staging I have branch called **develop**. Tags are usually behind the develop branch until its merged to production branch with a proper tag.
3.) No, deployotron deosn't fail in this condition, it only fails the sanity check due to permission change (and git takes the permission change as file modification). I learned how to disable the permission check by git, will try without `--insanity` as well...
4.) and 5.) will run tomorrow again and post it here.... Usually I didn't do `git checkout SHA` I used to do `git pull` directly in the server and run deploy again.... but yes, tomorrow morning...

**Comment by xendk** [comment]
Okay. It does seem that git thinks that's everything is as it should be, so especially `git show HEAD` just after the deploy is interesting. If that reports the sha which was supposed to be deployed, but the code doesn't reflect this, it's rather hard for Deployotron to catch the failure.

**Comment by rajibmp** [comment]
here I post the process from beginning...  
**before Deploy**
```js
git log
commit 1f473c100cb70cc9bd03435fef0757e57929e3bc
Author: Rajib Paudyal <rajib.mp@gmail.com>
Date:   Fri Apr 24 22:33:40 2015 +0300

git reflog
1f473c1 HEAD@{0}: checkout: moving from develop to 1f473c100cb70cc9bd03435fef0757e57929e3bc

git show HEAD
commit 1f473c100cb70cc9bd03435fef0757e57929e3bc
Author: Rajib Paudyal <rajib.mp@gmail.com>
Date:   Fri Apr 24 22:33:40 2015 +0300

```

**Deploy** without `--insanity`
```js
drush deploy @demo --branch=develop
About to:

1: Check that the deployed git repository is clean.

2: Set the site offline.

3: Dump database to /tmp/deploy.demo.2015-05-18T11:10:22.1f473c100cb70cc9bd03435fef0757e57929e3bc.sql.

4: Run git fetch and check out 1f473c100cb70cc9bd03435fef0757e57929e3bc:
   Rajib Paudyal <rajib.mp@gmail.com> @ 2015-04-24 22:33:40 +0300 (3 weeks ago)
   
   sites.php file deleted
   
   Currently deployed: 1f473c100cb70cc9bd03435fef0757e57929e3bc
   Rajib Paudyal <rajib.mp@gmail.com> @ 2015-04-24 22:33:40 +0300 (3 weeks ago)
   
   sites.php file deleted
   
   All changes:
   

5: Run command: ~/drush/drush -y fra --force

6: Create VERSION.txt.

7: Runs database updates (as with update.php).

8: Clear all Drupal caches.

9: Set the site online.

10: Not purging any dumps.


Continue? (y/n): y
Sanity checking                                                                                           [status]
                                                                                                          [ok]

Setting site offline                                                                                      [status]
maintainance_mode was set to "1".                                                                         [success]
                                                                                                          [ok]

Dumping database                                                                                          [status]
Database dump saved to /tmp/deploy.demo.2015-05-18T11:10:22.1f473c100cb70cc9bd03435fef0757e57929e3bc.sql [success]
                                                                                                          [ok]

Deploying                                                                                                 [status]
HEAD now at 1f473c100cb70cc9bd03435fef0757e57929e3bc                                                      [status]
                                                                                                          [ok]

Running command: ~/drush/drush -y fra --force                                                             [status]

********* Clipped the Feature Revert *************************

Creating VERSION.txt                                                                                      [status]
                                                                                                          [ok]

Running database updates                                                                                  [status]
No database updates required                                                                              [success]
'all' cache was cleared.                                                                                  [success]
Finished performing updates.                                                                              [ok]
                                                                                                          [ok]

Clearing caches                                                                                           [status]
'all' cache was cleared.                                                                                  [success]
                                                                                                          [ok]

Setting site online                                                                                       [status]
maintainance_mode was set to "0".                                                                         [success]
                                                                                                          [ok]


Done.

```

**After Deploy**
```js
git log
commit 1f473c100cb70cc9bd03435fef0757e57929e3bc
Author: Rajib Paudyal <rajib.mp@gmail.com>
Date:   Fri Apr 24 22:33:40 2015 +0300

*******************************
git checkout a83354e
Previous HEAD position was 1f473c1... sites.php file deleted
HEAD is now at a83354e... add a linebreak on the end of file to test deploytron

********************************
git log
commit a83354e48fa4a82741a5a0a5839dfda696d1f6d7
Author: Rajib Paudyal <rajib.mp@gmail.com>
Date:   Mon May 18 08:09:21 2015 +0000

    add a linebreak on the end of file to test deploytron

commit 1f473c100cb70cc9bd03435fef0757e57929e3bc
Author: Rajib Paudyal <rajib.mp@gmail.com>
Date:   Fri Apr 24 22:33:40 2015 +0300

    sites.php file deleted

**********************************
git show HEAD
commit a83354e48fa4a82741a5a0a5839dfda696d1f6d7
Author: Rajib Paudyal <rajib.mp@gmail.com>
Date:   Mon May 18 08:09:21 2015 +0000

    add a linebreak on the end of file to test deploytron

```

**Re-Deploy** again
```js
drush deploy @demo --branch=develop
About to:

1: Check that the deployed git repository is clean.

2: Set the site offline.

3: Dump database to /tmp/deploy.demo.2015-05-18T11:30:54.a83354e48fa4a82741a5a0a5839dfda696d1f6d7.sql.

4: Run git fetch and check out 1f473c100cb70cc9bd03435fef0757e57929e3bc:
   Rajib Paudyal <rajib.mp@gmail.com> @ 2015-04-24 22:33:40 +0300 (3 weeks ago)
   
   sites.php file deleted
   
   Currently deployed: a83354e48fa4a82741a5a0a5839dfda696d1f6d7
   Rajib Paudyal <rajib.mp@gmail.com> @ 2015-05-18 08:09:21 +0000 (22 minutes ago)
   
   add a linebreak on the end of file to test deploytron
   
   All changes:
    sites/all/themes/README.txt | 1 -
    1 file changed, 1 deletion(-)

5: Run command: ~/drush/drush -y fra --force

6: Create VERSION.txt.

7: Runs database updates (as with update.php).

8: Clear all Drupal caches.

9: Set the site online.

10: Purge the following dump files:
   /tmp/deploy.demo.2015-05-13T12:50:19.1f473c100cb70cc9bd03435fef0757e57929e3bc.sql.


Continue? (y/n): 
```

I have noticed something different in **Step 4** of Deploy, it says going back to previously deployed commit. The deploy process executes without error.

**Comment by rajibmp** [comment]
So, I guess the `git fetch` is working but it doesn't checkout the latest SHA.

**Comment by xendk** [comment]
In the second attempt it decides to deploy the previous commit, which shuould mean that the `develop` branch on the *local* machine points to `1f473c100`. Deployotron uses the local git repository to translate tags/branches to shas, in order to avoid unpleasant surprises. 

Try running `git pull` locally before deploying.

**Comment by rajibmp** [comment]
> Try running `git pull` locally before deploying.

That's what I have been doing till now.

Now looking at the whole point, I think either I should not pass the branch-name with deploy.  
As of now, git fetches the latest SHA from remote repo but instead of checking out the latest SHA it checks out the latest in local develop branch. Maybe I need to find different workflow for git repos. I'll try without branch-name...

**Comment by xendk** [comment]
That's odd. Doing a `git pull` should update your local branch (I'm assuming that `develop` is checked out in the local repository), which should make Deployotron see the latest commit to it and use the sha of that for deploying.

It's pretty much designed around the workflow of the developer doing code, merging it into `develop` (or whatever branch one uses for deployment) locally, pushing the branch and then running `drush deploy @alias`, but there shouldn't be any problem in doing a pull/deploy thing instead.

I was pondering making it default to use the sha that's currently checked out locally if `branch`/`tag`/`sha` wasn't specified in alias or the command line, but I might fear that it would mislead people to think that it will deploy the current content of the local checkout (including locally changed files and unpushed commits), rather than the exact same revision from the upstream repository.
