### ISSUE TITLE
Extend

### ISSUE THREAD

**Issue by richardbporter** [reload/deployotron#30]
Hi - First, great command!

I didn't see any docs on extending. Is there any way to execute additional actions before/after deploying?

Sorry if I missed something.

**Comment by xendk** [comment]
Thank you,

Getting Deployotron to directly run a command, the only option is to configure the restart apache2/varnish commands to do something entirely different. But that's quite a hack.

Alternatively, Deployotron can run drake https://www.drupal.org/project/drush_drake post update, which could do many things. But there's not a corresponding pre-update.

Being able to add in custom commands has been on the radar for some time, but it opens up for a lot of questions, so not much headway has been done yet.

**Comment by richardbporter** [comment]
Gotcha, thanks for the response.
