### ISSUE TITLE
Deploying annotated tags

### ISSUE THREAD

**Issue by richardbporter** [reload/deployotron#35]
When trying to deploy an annotated tag, I get the following message: 
```
Code not properly deployed, head is at {sha} now.
deploy code failed.
```
I haven't looked into this much and maybe its by design. Anyway, simple tags work fine.

**Comment by xendk** [comment]
Now that's odd. That should only happen if rev-parse HEAD !== rev-parse {tag}.

Is the sha it prints the sha of the annotated tag or the last deployed sha?

Deployotron shouldn't really care whether it's a branch, tag, annotated tag or sha, as long as rev-parse understand it. The branch/tag distinction is primarily for human consumption.

**Comment by richardbporter** [comment]
The `{sha}` in the error message is the last deployed SHA.

Haven't had time to investigate further yet!

**Comment by xendk** [comment]
So the code didn't get updated, but git checkout didn't fail either...

Just to make sure: it's a completely new tag, not one that's moved, right?

**Comment by richardbporter** [comment]
Yes, completely new tag.

`git tag -a v1.0 -m 'this is an annotated tag'`

Won't `rev-parse HEAD !== rev-parse {tag}` always fail because the annotated tag has its own SHA?

**Comment by xendk** [comment]
Indeed, that seems to be the issue.

Guess that pickSha need to double check whether the SHA it got is an annotated tag, and take SHA^ if it is. Haven't figured out the magic git commands yet though.

**Comment by richardbporter** [comment]
Looks like things have changed a bit, but would something like this work? 

https://github.com/reload/deployotron/commit/682ce46934e1b47a6a3253efb95b758e3e2d6d07

This worked with a branch/sha/tag in my own testing but the pickSha method could have more validation to only run this against tags.

**Comment by xendk** [comment]
Added test which tells me that it works. Waiting for Travis to give the all green (full tests worked locally though) and then I'll make a 2.0.1 release.
