### ISSUE TITLE
Argument 1 passed to Deployotron\Actions\PurgeDatabaseBackups::run() must be of the type array, object given, called in /Users/thomas/www/mysite/sites/all/drush/deployotron/deployotron.drush.inc on line 179 and defined deployotron.actions.inc:1001 

### ISSUE THREAD

**Issue by gielfeldt** [reload/deployotron#45]
You cannot use array type-hinting with ArrayObject.

**Comment by xendk** [comment]
Well, the type hint should be ArrayObject instead. Donno why I haven't gotten this before.

The reason why it's an ArrayObject:
https://github.com/reload/deployotron/blob/master/deployotron.drush.inc#L172

But maybe we should create a state object to make things more explicit. It could inherit from ArrayObject for starters.
